version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  blue:
    image: myapp:blue_v1
    environment:
      - NODE_ENV=production
  green:
    build: .
    environment:
      - NODE_ENV=production